### ISSUE TITLE
[Fabric 1.20.1] Game crashes when trying to render trinkets with no model

### ISSUE THREAD

**Issue by LauraRoseLuna** [emilyploszaj/trinkets#349]
I'm in the process of making a personal modpack for myself and some friends and I've run into an issue where Minecraft crashes after equipping items with no render model to a Trinket slot, particularly items from the Twilight Forest mod. Furthermore, I can no longer open my singleplayer testing world without rolling back my save because of it. The ID for the specific item I equipped is `twilightforest:charm_of_life_1` in case that helps.

```
Time: 2024-11-20 10:22:28
Description: Rendering entity in world

java.lang.IllegalArgumentException: No model for layer twilightforest:charm_of_life#main
	at knot//net.minecraft.class_5599.method_32072(class_5599.java:17)
	at knot//twilightforest.compat.trinkets.renderer.CharmOfLife1NecklaceRenderer.render(CharmOfLife1NecklaceRenderer.java:24)
	at knot//dev.emi.trinkets.TrinketFeatureRenderer.lambda$render$0(TrinketFeatureRenderer.java:24)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at knot//dev.emi.trinkets.TrinketFeatureRenderer.lambda$render$1(TrinketFeatureRenderer.java:22)
	at knot//dev.emi.trinkets.api.LivingEntityTrinketComponent.forEach(LivingEntityTrinketComponent.java:362)
	at knot//dev.emi.trinkets.TrinketFeatureRenderer.lambda$render$2(TrinketFeatureRenderer.java:21)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at knot//dev.emi.trinkets.TrinketFeatureRenderer.render(TrinketFeatureRenderer.java:20)
	at knot//dev.emi.trinkets.TrinketFeatureRenderer.method_4199(TrinketFeatureRenderer.java:12)
	at knot//net.minecraft.class_922.redirect$zpp000$apoli$preventFeatureRendering(class_922.java:1068)
	at knot//net.minecraft.class_922.method_4054(class_922.java:145)
	at knot//net.minecraft.class_1007.method_4215(class_1007.java:66)
	at knot//net.minecraft.class_1007.method_3936(class_1007.java:43)
	at knot//net.minecraft.class_898.method_3954(class_898.java:145)
	at knot//net.minecraft.class_761.method_22977(class_761.java:1574)
	at knot//net.minecraft.class_761.invokeRenderEntity(class_761.java)
	at knot//net.irisshaders.iris.shadows.ShadowRenderer.renderPlayerEntity(ShadowRenderer.java:672)
	at knot//net.irisshaders.iris.shadows.ShadowRenderer.renderShadows(ShadowRenderer.java:506)
	at knot//net.irisshaders.iris.pipeline.IrisRenderingPipeline.renderShadows(IrisRenderingPipeline.java:1022)
	at knot//net.minecraft.class_761.handler$flp000$iris$renderTerrainShadows(class_761.java:14052)
	at knot//net.minecraft.class_761.method_22710(class_761.java:1241)
	at knot//net.minecraft.class_757.method_3188(class_757.java:1110)
	at knot//net.minecraft.class_757.method_3192(class_757.java:880)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1219)
	at knot//net.minecraft.class_310.method_1514(class_310.java:802)
	at knot//net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

**Comment by emilyploszaj** [comment]
This is a twilight forest bug unfortunately
